### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-hoverable#29]
There is a media query for this now: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover

**Comment by gvonkoss** [comment]
But it doesn't have any IE support—does IE exist on devices like phones and tablets? 🤔

**Comment by notlee** [comment]
Looks like `o-hoverable` doesn't cater for IE + touch anyhow. It assumes the user can't hover if `ontouchstart` or `window.DocumentTouch` is supported. IE11 supports neither of these, so IE11 is already always treated as if the user can hover.

Also... `o-hoverable` uses touch support to assume the user can't hover. This isn't true for "convertible" devices like Microsoft's Surface, where touch and cursor input is possible.

**Comment by chee** [comment]
yes, i think so.

though, we could also improve it.

you can listen on `touchmove` and `pointermove` and then decide whether the person can hover based on that.

this way, if they are using a device with multiple inputs, it will only start allowing hovers once they used a device that can hover.

```js
document.addEventListener("mousemove", function mousey() {
  htmlClassList.add(className)
  document.removeEventListener("mousemove", mousey)
})

document.addEventListener("pointermove", function pointy(event) {
  if (event.pointerType == "mouse") {
    htmlClassList.add(className)
    document.removeEventListener("pointermove", pointy)
  }
})
```

that supports back to IE11.

i see in the code here that it's using MSPointerHover, which i think means it's trying to support IE10?

**Comment by notlee** [comment]
Great points. 👏 But I think it solves a problem we don't really have.

Only three-ish components use o-hoverable:
- o-overlay
- o-gallery
- o-hierarchical-nav (going to be deprecated, now o-header-services has dropdowns)

They prevent the hover state of their buttons when touched. That can be achieved with native CSS in most cases. If a user has both input types, reducing the chance we'll show the hover on touch isn't worth maintaining or executing o-hoverable ¯\_(ツ)_/¯

**Comment by chee** [comment]
> if a user has both input types, reducing the chance we'll show the hover on touch isn't worth maintaining or executing o-hoverable ¯\\_(ツ)_/¯


:fire: ++yes :fire:

**Comment by notlee** [comment]
Done!
